# docker-compose.yml
version: '3'

services:
  app:
    image: finware-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finware-node-app
    environment:
      - PORT=${PORT}
      - DB_URL=${DB_URL}
      - LOCAL_SECRET=${LOCAL_SECRET}
    working_dir: /usr/src/app
    ports:
      - '${PORT}:${PORT}'
    networks:
      - finware-network
  db:
    image: postgres
    container_name: pg-docker
    environment:
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=pg5432
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - finware-network
volumes:
  pgdata:
networks:
  finware-network:
    driver: bridge
